<a href="https://colab.research.google.com/github/kekubhai/agents1/blob/main/pytorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("I am anirbaan here to learn PYTORCH")


I am anirbaan here to learn PYTORCH


In [1]:
import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
#tensors
scaler=torch.tensor(7)
print(scaler)
scaler.ndim



tensor(7)


0

In [ ]:
 #matrix
 MATRIX =torch.tensor([[7,8], [4,2]])
 MATRIX
 MATRIX.shape

torch.Size([2, 2])

In [ ]:
tensor=torch.tensor([[[1,2,4],[4,566,4],[87,34,754],[3,3,3]]])
tensor.shape


torch.Size([1, 4, 3])

In [ ]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim






(torch.Size([224, 224, 3]), 3)

In [ ]:
int_32_tensor=torch.tensor([2,4,5],dtype=torch.long)
int_32_tensor

tensor([2, 4, 5])

In [ ]:
tensor=torch.tensor([2,46,12])
tensor+10

tensor([12, 56, 22])

In [3]:
tensor=torch.tensor([1,2,3])
#pytorch inbuilt function
torch.mul(tensor,10)




tensor([10, 20, 30])

In [8]:
tensor_A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_B=torch.tensor([[11,12.13],[14,15,16],[17,18,19]]



































                      )
torch.matmul(tensor_A,tensor_B)






ValueError: expected sequence of length 2 at dim 1 (got 3)

In [15]:
import torch
x=torch.arange(1., 10.)
x, x.shape
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [19]:
z=x.view(1,9)
z,z.shape

x_stacked=torch.stack([x,x,x,x])
x_stacked

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])